### PR TITLE
Update travis CI tests to >= PHP 5.6

### PR DESCRIPTION
**Pull request by dnsmichi**

### CODE REVIEW

**Comment by dnsmichi** [comment]
@lippserd just saw that tests were failing in #180 because of this.

**Comment by lippserd** [comment]
I don't see why we should keep the tests for 5.4 and 5.5. This is a Web 2 module and Web 2 requires at least version 5.6.

**Comment by Thomas-Gelf** [comment]
From [Installation requirements](https://github.com/Icinga/icingaweb2-module-businessprocess/blob/master/doc/01-Installation.md#requirements): 

* Icinga Web 2 (>= 2.4.1)
* PHP (>= 5.3 or 7.x)

I do not see why a bugfix release should require this to be changed, especially since we have quite some consulting/support customers still running 2.4.x. As far as I know mostly for simple reasons, like 2.5.x breaking their themes or LDAP issues with some versions.

Of course everybody should always upgrade to the latest and greatest and safest version. However, reality out there often looks different. I'm personally against breaking compatibility and annoying users unless there are good reasons to do so. Most of the times it costs very little effort to do so.

**Comment by dnsmichi** [comment]
I just saw that [2.2.0](https://github.com/Icinga/icingaweb2-module-businessprocess/milestone/6) would be the next feature release. The docs update will come when this PR is merged.

**Comment by lippserd** [comment]
As @dnsmichi said, the next release is a feature release.
I think it's best to raise the minimum Web 2 dep to version 2.5.1 because at least PR #171 relies on it.
And since Web 2 2.5.x requires PHP 5.6, it makes sense to move on in this module as well.

@dnsmichi Could you please keep the Web 2 version at 2.5.1 in the tests?

**Comment by dnsmichi** [comment]
@lippserd sure, here you go :)

**Comment by Thomas-Gelf** [comment]
@lippserd: as far as I remember we agreed on requiring 5.6 while keeping tests running on 5.4. That's what we're still doing in our `ipl` repositories, but of course sooner or later we might be forced to break this. Currently the only serious candidate would be `yield`, and we could still structure our libraries in a way allowing 5.4 to run.

Back to this repository, you can them as `allow_failures` like we do in the ipl. This would at least help us to figure out when we broke it. Btw, Icinga Web v2.5.x states to be compatible with 5.3. However, we all agree that 5.3 is more than dead. 5.4 is no longer supported, but the default version on some of our supported distributions. And to me, that's a problem. We're still seeing people running either the CLI or the web on 5.4, even while installing our packages. They often are not even aware of doing so, our packages didn't adjust their configuration.

There is no technical reason for a simple module like businessprocess to break 5.4, IMO also web2 shouldn't. And please note that `breaking != supporting`. I have no problem with not officially supporting anything older than 5.6 - but I'm against breaking it for no good reason.

Cheers,
Thomas

**Comment by dnsmichi** [comment]
I'm seeing lots of people having a mix of PHP 5.4 and PHP5.6 (or 7.x) on the community forums, and some of them never recognized that 5.6 is the new main requirement, still running on 5.4 without knowing that. Only after password_verify() being dropped and throwing ugly stack traces now. That really is a pain to find out with question-answer ping-pong, I would like to save that time.

Imho keeping support for versions older than 5.6 will just make things more complicated, and the mix of modules doing things differently than the leading framework (Icinga Web 2) will complicate things even more. Not only for developers switching projects but also for those doing support, for partners and in the community. We should settle with a general least requirement for all our modules and release new major versions based on that, imho PHP 5.6+ and Icinga Web 2 v2.5+.

Cheers,
Michael

**Comment by Thomas-Gelf** [comment]
@dnsmichi: that's exactly what I'm also seeing. This tells me that we should work harder on getting our tools shipped in a way allowing them to make users aware of such problems. Our upgrade paths must become smoother. One more reason to make sure our code keeps running on 5.4.x. Otherwise we would not be able to show meaningful warnings with instructions of how to upgrade. 

Sometimes this is hard, sometimes it is easy. Usually it costs very little effort to still support the "old world". Rarely ever one needs to ship proxy classes for slightly different implementations. Sometimes it's required to ship a polyfill. Sometimes nothing would help, sometimes we have to completely drop support for a specific version. We would all love to write for 7.2 only, we strongly suggest 7.x everywhere because it is way faster than 5.x. We support 5.6 as it is running on many systems, this is what we communicate as a minimum requirement. But to me that doesn't imply that we should immediately break 5.4 unless there are good reasons of doing so.

PHP 5.3 is a good example, because 5.3 and 5.4 differ extremely. Much more than 5.4 and 5.6. Director for example still fully supports 5.4 and will at continue to do so at least with v1.5.x. On the other side, it was our first module dropping support for 5.3 for various reasons. That was our experiment to figure out how the community accepts such changed requirements. But Director did so in a very smooth way.

The problem was that even code as simple as `$a = [];` results in a parse error on 5.3. The solution there was to route requests on 5.3 in a completely different way - because not even the simplest Director controller is able to run on 5.3. Not very elegant, but extremely helpful. To the user it looks like this:

director_php53error

That's how IMHO all our tools should behave in case there is no other way. When in doubt, the preference should be to keep fully running on legacy systems. The alternative here would have been `Parse error: syntax error, unexpected '[' in [...]/ConfigController.php`. What would you prefer to see when upgrading software on your systems?

I'm perfectly fine with us stating that we do no longer support PHP less than 5.6.x. But I'd strongly suggest to still keep our tests running on 5.4 and to pay attention not to break things. There are not enough tests, especially for the frontend. But just `phpcs` alone protects you from most errors. It makes sure that we do not ship code that cannot be parsed at all. That way every time someone reaches a point where he would break 5.4 he can opt on whether it would be less pain to fix the issue or to start a discussion whether the time to completely break 5.4 is now ;-)

I guess we all agree that what of course should not happen is a web front-end throwing ugly exceptions because of such a non-reason. To pick your concrete example, there are zillions of tutorials and code snippets out there showing how to provide `password_verify` in a compatible way to older PHP versions. That alone never ever qualifies as a reason to drop support for 5.4.

The problem here is that we don't care enough, and that we get used to doing so. This is a problem of culture, not a technical one. We are not bad at all when it goes to keeping compatibility, but we could do a way better job throughout all of our products. To get there, we need more awareness for this issue. It's not getting better when we teach our developers that not caring about legacy systems is the fine per default. By the end of the day, it's monitoring software. From an operators perspective not being required to care at all would be the best that could happen. Monitoring should just be there, silent, boring, but always up and running. And it should protect your ass every time the house is on fire.

Thomas.

**Comment by lippserd** [comment]
I got your point that it makes sense to support 5.4+ because Web 2 2.5.1 as the minimum dependency also still supports 5.4+.

**Comment by dnsmichi** [comment]
@Thomas-Gelf I understand your good intentions with this and I appreciate it. Still, for me being very active on the community channels this mix of required versions is somewhat problematic and I am looking for ways to make it more visible and simple. Like the support matrix @bobapple added to icinga.com, there should be a general requirement.

Say, Icinga Web 2 2.5+ is required for this module, therefore it automatically inherits the requirement to  support that PHP version. It may be an idea to move the requirement checks (PHP, datetime, etc.) from the `setup` module into Icinga Web 2 "core" itself and call that during bootstrap. Similar to what the Director already does in its own.

Cheers,
Michael

**Comment by Thomas-Gelf** [comment]
Thanks @dnsmichi! Our capability to mix versions is a very valuable feature, we should keep following that path. I'm strictly against using such support matrix as an excuse for becoming lazy in this point.

I want us to develop a better culture when it goes to keeping compatibility. For example in my believes we cannot state to **Monitor any Infrastructure and any Application** while deprecating our Agent for Operating System as soon as they are out of support. Sometimes a break is required, as new dependencies are added. But the we should then still be able to tell people that "Agent 2.x is compatible with Master 2.z". You can hardly say "Upgrade all your 10.000 Servers and drop all Windows 2000 Servers driving your automotive production lines". The web is easier, as it is reasonable to say "Upgrade your master OS". 

However, Icinga Web 2 still works with Icinga 1 - and this is very important for many users. Imagine Web 2.6 would break this, it would force them to stay on 2.5. Now let's say such user upgrades the bp module from 2.1 to 2.2, because 2.2 fixes an important issue. But that one fails on 2.5. Now what?

And that's just a very simple example, we ship lot's of modules, lot's of interaction. There will always be some reason someone might not be able to upgrade all of them at once. And often it could be our fault, without even realizing it. A culture/policy focusing on "compatibility first" prevents us from running into needless trouble. Upgrades not asking for interaction that "just work" without any issues are the best way to lower support efforts on our community channels.

Thomas.

**Pull request merged**
