### PR TITLE
WIP: module.less: Improve the color scheme of Nodes

### PR DESCRIPTION
**Pull request by lazyfrosch**
With suggestions from @flourish86, thank you!

should fixe #135

### CODE REVIEW

**Comment by lazyfrosch** [comment]
bildschirmfoto von 2017-06-01 19-12-41
bildschirmfoto von 2017-06-01 19-11-37

**Comment by lazyfrosch** [comment]
We will likely ship the new foreground colors (text on top of icinga status colors) as part of the main theme.

So the CSS variables can be overwritten by a theme or similar.

Pending PR to icingaweb2

**Comment by Al2Klimov** [comment]
Hello @lazyfrosch,

What "Pending PR to icingaweb2" do you speak about? Is it required for this one to be merged?

Best,
AK

**Comment by lazyfrosch** [comment]
@Thomas-Gelf suggested to bring those foreground colors to the main Icinga Web 2 theme...

**Comment by Al2Klimov** [comment]
As discussed w/ @lazyfrosch (offline):

1. There's no actual PR in IW2.
2. I should ask @lippserd what to do.

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: as far as I can recall, the suggestion was to *first* introduce colors with a specific name in Icinga Web 2 and *then* use those names in our modules. 2.5 would have been a good occasion for doing so ;-)

I wouldn't hardcode colors into module CSS. We already did so, and it never turned out to be a good idea. Said all this, the feature/pull request for Web 2 should introduce foreground and related background colors for specific use cases with related names.

**Comment by lippserd** [comment]
Hi Markus,

This is superseded by #176. Thanks for the initial work on this.

Cheers,
Eric

**Pull request closed without merging**
