### PR TITLE
Feature/update styles

### LINKED ISSUE #135: Increase size of tiles dynamically
Hello,
as we have the overview of the business process nodes shown on a TV-screen, it should be readable by everyone, who looks at it. If we have only a few nodes, the size is very small to read.
So it would be nice, if the tile size would adapt itself based on the free space and based on the sum of tiles.
It should be zoomed in, until you would have to scroll, in order to see the next element.
Of course you would have to define a minimum size.
What do you think about this feature?

### PR DESCRIPTION
**Pull request by theFeu**
This is my suggestion for fixing the problem that lead to #141 but also incorporating the added info-url from #155 :)

fixes #135

### CODE REVIEW

**Comment by theFeu** [comment]
This is what it is going to look like:

image

**Comment by flourish86** [comment]
* Increasing the title font is a good choice.

I'd suggest the following changes:
* Please remove the text-shadow on the title or use the appropriate foreground colours from #141, as it causes noise (which is scientifically proven to cause eye cancer 😉)
* Please restore the transparency of the icons in the top left corner, so the visual focus is on the titles

The screenshot doesn't show how handled tiles look. In #141 we established foreground colors, which enabled us to avoid white text on light background-colours.

As discussed offline:
* Position the Badges in the bottom right (centering things in boxes usually looks awkward)
* Change the '?' icon to an 'i', something like Font Awesome's `info-circle`

Besides that, I still see a problem in rainbow coloured badges on solid color backgrounds (esp. green and red, violet and red). But let's keep them as far as we found an appropriate solution.

**Comment by theFeu** [comment]
image

@flourish86 updated version

**Comment by theFeu** [comment]
image

This is the draft with the background behind the badges @flourish86

**Comment by dnsmichi** [comment]
Top 👍

**Comment by flourish86** [comment]
The white bar makes taking the whole width makes the overall appearance noisy. It's also distracting from the title too much.

1. Maybe you could try to narrow down the badge background box to the badges width, so it won't span across the whole with.
2. Please remove the box, when there are no badges

**Comment by theFeu** [comment]
image

final design?

**Pull request merged**
